# ---------- Frontend DEV (Vite) ----------
FROM node:22 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

ENV NODE_ENV=development
ENV HOST=0.0.0.0
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]